#!/bin/bash

echo "This prog need to uninstall opstkhelp-ustils"
echo "It will delete all the added rc-zones along with their files and added passwords"
echo -n "Enter 'y' if you want to do this: "
read USERS_ANSWER

if [[ "$USERS_ANSWER" == "y" ]]
then
  rm -rf ${HOME}/.opstkhelp
  LOCAL_BIN_PATH=$(echo $PATH | sed 'y/:/\n/' | grep $(whoami))
  for BIN_PATH in ${LOCAL_BIN_PATH}
  do
    rm -f $(find ${BIN_PATH} -name "opstkhelp-*")
  done
  
  echo "Succesfully"
  exit 0
fi

echo "Unsuccessfully"
exit 1