#!/bin/bash

### This prog need to start or stop servers
### Functionality:
### 1) Print help : opstkhelp-manage-server -h, --help
### 2) Start or stop server from specified rc-zone: opstkhelp-manage-server -z ZONE_NAME ['start'|'stop'] SERVER_NAME
### 3) Start or stop all servers (from all added rc-zones) with specified name: opstkhelp-manage-server -a ['start'|'stop'] SERVER_NAME
### 4) Start or stop server (without information about rc-zone): opstkhelp-manage-server ['start'|'stop'] SERVER_NAME
### -- Update all servers-lists files of all zones
### 5) Start or stop server (without information about rc-zone): opstkhelp-manage-server -w ['start'|'stop'] SERVER_NAME
### -- Not update servers-lists files
### Other usage should return an error
### 1) If the '-z' flag is used with other flags, then these flags are ignored

# Add shared for all prog from package (for all opstkhelp-*) vars and performs general functions
source ${HOME}/.opstkhelp/init.sh

display_help(){
  echo -e "Usage: opstkhelp-manage-server [OPTIONS] ['start'|'stop' SERVER-NAME]"
  echo -e "Usage: opstkhelp-manage-server [OTHER-OPTIONS]\n"
  echo -e "Manage selected server (start or stop)\n"
  echo -e "[SERVER-NAME] - name of target server\n"
  echo -e "[OTHER-OPTIONS]:"
  echo -e "-h, --help            Get this page.\n"
  echo -e "[OPTIONS]:"
  echo -e "-z                    Specify rc-zone for this server."
  echo -e "                      If this flag is specified, the other flags are ignored."
  echo -e "-a                    If the server's rc-zone is not specified (-z, --rc-zone flag),"
  echo -e "                      this flag will perform the necessary action with servers that have specified name"
  echo -e "                      from all zones. If server's rc-zone was specified then that flag will be ignored."
  echo -e "-w                    By default, without using the -z (--rc-zone) flag, the program updates the servers-lists (cache) files of all zones."
  echo -e "                      This behavior can be disabled using this flag. Use this flag only if you are sure"
  echo -e "                      that the list of servers has not been updated since the last updates the servers-lists files of all zones."
  echo -e "Examples:"
  echo -e "opstkhelp-manage-server -z ZONE_NAME start SERVER_NAME"
  echo -e "--- Start server named SERVER_NAME located in zone named ZONE_NAME."
  echo -e "opstkhelp-manage-server -a stop SERVER_NAME"
  echo -e "--- Stop server named SERVER_NAME."
  echo -e "--- If servers with this name are found in multiple zones,"
  echo -e "--- all of them will be stopped."
  echo -e "opstkhelp-manage-server -w start SERVER_NAME"
  echo -e "--- Start a server with this name located in any of the added zones."
  echo -e "--- If multiple servers with this name are found in the servers-list (cache), an error will be generated."
  echo -e "opstkhelp-manage-server -w -a start SERVER_NAME"
  echo -e "--- Start server named SERVER_NAME located in any zone."
  echo -e "--- Using servers-lists (cache) to find the right zones."
}

display_usage_error(){
  echo -e "Usage error\nUse:\nopstkhelp-manage-server --help" >&2
}

### Manage rc-zone 
### Return 0 if no errors were found
### Return 1 if an error occurred while executing the command
### Usage: manage_rc_zone_server_with_error_check [RC_ZONE_NAME] [SERVER_NAME] [SERVER_ACTION]
manage_rc_zone_server_with_error_check(){
  # Server management
  # Return MANAGE_RC_ZONE_SERVER var contains stderr of OpenStack API command
  manage_rc_zone_server "$1" "$2" "$3"

  # Error was occured
  if [[ "$?" -eq "1" ]]
  then
    echo "There was a problem with server '$2' from rc-zone '$1':" >&2
    echo "$MANAGE_RC_ZONE_SERVER" >&2
    return 1
  fi

  # If no errors occurred 
  echo "Server '$2' from rc-zone '$1' was $3 successfully"
  return 0
}

# User need help
# [opstkhelp-manage-server --help] or [opstkhelp-manage-server -h]
if [[ ("$1" == "-h" || "$1" == "--help") && "$#" -eq "1" ]]
then
  display_help # Func
  exit 0
fi

# Vars initialization

# Values:
# '1') if flag '-a' is set
# other) if flag '-a' isn't set
ARG_ALL_SERVERS_FLAG="0"

# Values:
# '1') if flag '-w' is set
# other) if flag '-w' isn't set
ARG_USE_CASHE_FLAG="0"

# Zone name arg (if flag '-z' are used)
ARG_RC_ZONE_NAME=""

# Server name arg
ARG_SERVER_NAME=""

# Server action arg ('start' or 'stop')
ARG_SERVER_ACTION=""

# Flags parsing
while getopts "z:aw" opt &> /dev/null
do
  case "$opt" in
    z)
      check_flag_arg "$OPTARG"
      if [ "$?" -eq "1" ]
      then
        display_usage_error
        exit 1
      fi

      ARG_RC_ZONE_NAME="$OPTARG"
      ;;
    a)
      ARG_ALL_SERVERS_FLAG="1"
      ;;
    w)
      ARG_USE_CASHE_FLAG="1"
      ;;
    \?)
      display_usage_error
      exit 1
      ;;
  esac
done

# If in the end of the arguments list not found ['start'|'stop' SERVER_NAME]
if [[ $((OPTIND - 1 + 2)) -ne "$#" ]]
then
  display_usage_error
  exit 1
fi

# Shift prog args to arg ['start'|'stop']
shift $((OPTIND - 1))

ARG_SERVER_ACTION="$1"
ARG_SERVER_NAME="$2"


if [[ "$ARG_SERVER_ACTION" != "start" ]] && [[ "$ARG_SERVER_ACTION" != "stop" ]]
then
  echo -e "Command '$ARG_SERVER_ACTION' not found" >&2
  echo -e "To get help use:\nopstkhelp-manage-server --help" >&2
  exit 1
fi

# Manage server from specified rc-zone
# [opstkhelp-manage-server * -z ZONE_NAME 'start'|'stop' SERVER_NAME] (* - other flags)
if [[ "$ARG_RC_ZONE_NAME" != "" ]]
then
  # Search this zone in rc-zones file
  check_rc_zone_name_correctness "$ARG_RC_ZONE_NAME"

  # Check rc-zone pass
  check_rc_zone_pass_correctness "$ARG_RC_ZONE_NAME"

  # Search server in rc-zone
  check_server_rc_zone_correctness "$ARG_RC_ZONE_NAME" "$ARG_SERVER_NAME"

  # Server management
  manage_rc_zone_server_with_error_check "$ARG_RC_ZONE_NAME" "$ARG_SERVER_NAME" "$ARG_SERVER_ACTION"

  # Error was occured
  if [[ "$?" -eq "1" ]]
  then
    exit 1
  fi

  # No errors occured
  exit 0

# If rc-zone not specified (not find flag '-z')
# [openstack-manage-server * 'start'|'stop' SERVER_NAME] where * is '-a' or/and '-w' or ''
else
  # Get all rc-zones containing the server named as ARG_SERVER_NAME var
  # Use cache ('-w' flag) or not determined by the value of ARG_USE_CASHE_FLAG var
  # Return array named GET_SERVER_RC_ZONES (numbering from zero)
  get_server_rc_zones "$ARG_SERVER_NAME" "$ARG_USE_CASHE_FLAG"
  ZONES_NUM="${#GET_SERVER_RC_ZONES[*]}"

  # No rc-zones were found
  if [[ "$ZONES_NUM" -eq "0" ]]
  then
    echo -e "No rc-zones containing the server named '$ARG_SERVER_NAME' were found\n" >&2
    echo -e "Verify the server name is correct" >&2
    # If user use cache (servers-list file)
    if [[ "$ARG_USE_CASHE_FLAG" -eq "1" ]]
    then
      echo -e "Or try to use openstack-manage-server without '-w' flag\n" >&2
    fi
    echo -e "For display all added servers use:" >&2
    echo -e 'for RC_ZONE in $(opstkhelp-get-info); do opstkhelp-get-info ${RC_ZONE}; done' >&2
    exit 1
  fi

  # More then one rc-zone were found
  # If flag '-a' wasn't found then display error
  # If flag was found then manage server
  if [[ "$ZONES_NUM" -ne "1" ]]
  then
    # If flag '-a' wasn't found then display error
    if [[ "$ARG_ALL_SERVERS_FLAG" -eq "0" ]]
    then
      echo -e "The server '$ARG_SERVER_NAME' was found in several zones:" >&2
      echo -e "${GET_SERVER_RC_ZONES[*]}\n" >&2
      echo -e "Specify rc-zone using '-z' flag or use '-a' flag to choose all zones\n" >&2
      echo -e "To get help use:\nopstkhelp-manage-server --help"
      exit 1
    fi

    ERROR_FLAG="0"
    for RC_ZONE_NAME in ${GET_SERVER_RC_ZONES[*]}
    do
      manage_rc_zone_server_with_error_check "$RC_ZONE_NAME" "$ARG_SERVER_NAME" "$ARG_SERVER_ACTION"
      if [ "$?" -eq "1" ]
      then
        ERROR_FLAG="1"
      fi
    done

    # If errors were occured
    if [ "$ERROR_FLAG" -eq "1" ]
    then
      exit 1
    fi

    # If errors were not occured
    exit 0
  fi

  manage_rc_zone_server_with_error_check "${GET_SERVER_RC_ZONES[0]}" "$ARG_SERVER_NAME" "$ARG_SERVER_ACTION"

  # Error was occured
  if [[ "$?" -eq "1" ]]
  then
    exit 1
  fi

  # No errors occured
  exit 0
fi

# Usage error
# Other [opstkhelp-manage-server *]
display_usage_error # Func
exit 1