#!/usr/bin/env bash

# BIN_FILES_PATH - the directory where they were installed opstkhelp-*
source ${HOME}/.opstkhelp/vars.sh

echo "This prog need to uninstall opstkhelp-utils"
echo "It will delete all the added rc-zones along with their files and added passwords"
echo -n "Enter 'y' if you want to do this: "
read USERS_ANSWER

if [[ "$USERS_ANSWER" == "y" ]]
then
  rm -rf ${HOME}/.opstkhelp
  rm -f $(find ${BIN_FILES_PATH} -name "opstkhelp-*")
  echo "Succesfully"
  exit 0
fi

echo "Unsuccessfully"
exit 0