# Local storage vars
LOCAL_DIR="${HOME}/.opstkhelp"
SUBFUNCTIONS_PATH="${LOCAL_DIR}/subfunctions"
RC_FILES_STORAGE_PATH="${LOCAL_DIR}/rc-files"
RC_ZONE_CONFIG_PATH="${LOCAL_DIR}"
PASSWORDS_STORAGE_PATH="${LOCAL_DIR}/rc-passwords"
SERVERS_LISTS_STORAGE_PATH="${LOCAL_DIR}/servers-lists"
SHARED_PASSWORD_HASH_PATH="${LOCAL_DIR}"

# Installation vars
REQUIREMENTS_PATH="./subfiles"